// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD29dnV6m4jDlFi2cqqgY9qZdNqPZjOOpw',
    appId: '1:822547938697:android:4fd0c29fe0e9e82a8ff558',
    messagingSenderId: '822547938697',
    projectId: 'money-c63dd',
    storageBucket: 'money-c63dd.firebasestorage.app',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaVmAgUvuXwjdg3rD3nL0HFRjQabgR4YE',
    appId: '1:822547938697:ios:5c27d96c00e6c6608ff558',
    messagingSenderId: '822547938697',
    projectId: 'money-c63dd',
    storageBucket: 'money-c63dd.firebasestorage.app',
    androidClientId: '822547938697-733mc5k5ge7iha443be5a3l34d5pfbvb.apps.googleusercontent.com',
    iosClientId: '822547938697-ahdr6vu2eiqe3hllltvcq1enipbrqpf8.apps.googleusercontent.com',
    iosBundleId: 'com.probiotics.money',
  );
}
